<a href="https://colab.research.google.com/github/Dikesh123-eng/Python-Programming/blob/main/day6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#creating 1D array
import numpy as np
arr=np.arange(1,10)
print(arr)


[1 2 3 4 5 6 7 8 9]


In [12]:
a = [2, 4, 8, 3]
b=[]

for i in a:
    b=(arr[i]*3)
    print(b)


9
15
27
12


In [13]:
#Adding Two array
import numpy as np
arr=np.arange(1,10)
arr2=np.arange(1,10)
print(arr+arr2)

[ 2  4  6  8 10 12 14 16 18]


In [27]:
import numpy as np
arr=np.arange(1,10)
arr2=np.arange(1,10)
#max values
print(" maxium no is:",np.max(arr))
#min values
print(" minium no is:",np.min(arr))
#product values
print(" productis:",np.prod(arr))
#sum
print(" sum is:",np.sum(arr))
#min values in first axies
print(" minium no in first axies:",np.min(arr,axis=0))
#find maximum values in first axies
print(" maxium no in first axis is:",np.max(arr,axis=0))
# find mean
print("mean is :",np.mean(arr))
# find median
print("meadian is :",np.median(arr))
# for random value
a_random=np.random.randint(11,100,24)
print(a_random)
print()
#rehape this value
a_random=np.random.randint(11,100,24).reshape(6,4)

print(a_random)






 maxium no is: 9
 minium no is: 1
 productis: 362880
 sum is: 45
 minium no in first axies: 1
 maxium no in first axis is: 9
mean is : 5.0
meadian is : 5.0
[39 89 37 82 80 89 23 95 14 92 48 82 63 85 18 80 50 26 35 30 54 57 39 20]

[[91 89 12 93]
 [83 79 47 70]
 [41 84 70 71]
 [13 73 12 71]
 [17 76 91 41]
 [29 23 75 63]]


In [31]:
#pandas
#creating pandas
import pandas as dikesh
a = [1,2,3,"hello"]

list = dikesh.Series(a)

print(list)
print(type(list))



0        1
1        2
2        3
3    hello
dtype: object
<class 'pandas.core.series.Series'>
0        1
1        2
2        3
3    hello
dtype: object
<class 'pandas.core.series.Series'>


In [34]:
#pandas
#creating pandas
import pandas as dikesh
devices={0:"laptop",1.:"camera",3:"phone",4:"printer"}
data= dikesh.Series(devices)
print(data)






0.0     laptop
1.0     camera
3.0      phone
4.0    printer
dtype: object


In [36]:
#
import pandas as pd
devices=["laptop"," camera"," phone"," printer"]
price=[350000,550000,450000,670000]
data=pd.Series(price,index=devices)
print(data)

laptop      350000
 camera     550000
 phone      450000
 printer    670000
dtype: int64


In [39]:
import pandas as pd
data={"computer":"Rs:35000","camera":"Rs:5550000"," phone":"Rs560000"}
data1=pd.Series(data)
print(data1)


computer      Rs:35000
camera      Rs:5550000
 phone        Rs560000
dtype: object


In [42]:
#define name series
import pandas as pd
data={"computer":"Rs:35000","camera":"Rs:5550000"," phone":"Rs560000"}
data1=pd.Series(data)
print(data1)
Data_series=pd.Series(data1,name=" Apana Dukan")
Data_series


computer      Rs:35000
camera      Rs:5550000
 phone        Rs560000
dtype: object


computer      Rs:35000
camera      Rs:5550000
 phone        Rs560000
Name:  Apana Dukan, dtype: object

In [46]:
data={"computer":"Rs:35000","camera":"Rs:5550000"," phone":"Rs560000"}
data1=pd.Series(data)
print(data1)
Data_series=pd.Series(data1,name=" Apana Dukan")
print(" Size is:",Data_series.size)


computer      Rs:35000
camera      Rs:5550000
 phone        Rs560000
dtype: object
 Size is: 3


In [ ]:
#name of data series
data={"computer":"Rs:35000","camera":"Rs:5550000"," phone":"Rs560000"}
data1=pd.Series(data)
print(data1)
Data_series=pd.Series(data1,name=" Apana Dukan")
print(" Size is:",Data_series.name)



In [53]:
#upload  csv file
import pandas as pd

data=pd.read_csv('1.csv',encoding="ISO-8859-1")
print(data)


                                 description  \
0                 Total number of businesses   
1                 Total number of businesses   
2                 Total number of businesses   
3                 Total number of businesses   
4                 Total number of businesses   
...                                      ...   
11134  Contact with Callaghan Innovation: No   
11135  Contact with Callaghan Innovation: No   
11136  Contact with Callaghan Innovation: No   
11137  Contact with Callaghan Innovation: No   
11138  Contact with Callaghan Innovation: No   

                               industry  level             size line_code  \
0                                 total      0   6–19 employees       NaN   
1                                 total      0  20–49 employees       NaN   
2                                 total      0  50–99 employees       NaN   
3                                 total      0   100+ employees       NaN   
4      Agriculture, forestry, & fishin