<a href="https://colab.research.google.com/github/Dikesh123-eng/Python-Programming/blob/main/ihub_trainee.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# combine two list
l1=[1,2,3,4,5]
l2=[3,6,7,8,9]
def listprint(l1,l2):
 return l1+l2
print(listprint(l1,l2))

[1, 2, 3, 4, 5, 3, 6, 7, 8, 9]


In [10]:
print(*range(1,10))


1 2 3 4 5 6 7 8 9


In [29]:
#print square 1 to 20
list=[i*i for i in range(1,21)]
print(list)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]


In [30]:
 #printing even no
list=[i  for  i in range(1,11) if i%2==0]
print(list)

[2, 4, 6, 8, 10]


In [31]:
#print th list taking user through input
l1=[]
for i in range(int(input("enter your size of list"))):
    num=int(input("enter your no here:"))
    l1.append(num)
    print(num)

enter your size of list5
enter your no here:4
4
enter your no here:5
5
enter your no here:7
7
enter your no here:3
3
enter your no here:8
8


In [12]:
l1=[1,2,3,4,5]
for i in l1:
  print(i*i)

1
4
9
16
25


In [27]:

#cartesion prpducts
l1=[1,2,3,4]
l2=[5,6,7,8]
x=[i*j for i in l1 for j in l2]
print(" product is",x)



 product is [5, 6, 7, 8, 10, 12, 14, 16, 15, 18, 21, 24, 20, 24, 28, 32]


#### NUMPY######
-> Numpy is a python library
-> it is a homogenious datatype
->non- globlal
-> faster than list
-> It  has array called ndarray
it is not posssible in numpy not possible size of in nd array ,if you try the orginal array will be deletd
and the new array will be created
 # for numpy
 import numpy as np

In [50]:
import numpy as np
#creating 1-D array

l1=[1,3,5,6,7,8]
print(type(l1))
nd=np.array(l1)
print(type(nd))
print(nd)

<class 'list'>
<class 'numpy.ndarray'>
[1 3 5 6 7 8]


In [47]:
import numpy as np
#creating 2-D array
l2=[[1,2,3],[2,7,8]]

nd2=np.array(l2)
print(type(nd))
print(l2)

<class 'numpy.ndarray'>
[[1, 2, 3], [2, 7, 8]]


In [54]:
#creating 3-D array
import numpy as np
l3=[[1,2,3],[4,6,7],[9,8,6]]
nd3=np.array(l3)
print(type(nd))
print(nd3)


<class 'numpy.ndarray'>
[[1 2 3]
 [4 6 7]
 [9 8 6]]


In [55]:
#convert int to float
import numpy as np
l1=[1,3,4,5,6]
np_typ=np.array(l1,dtype=float)
print(np_typ)


[1. 3. 4. 5. 6.]


In [63]:
#convert int to bool
import numpy as np#dikesh
l1=[1,3,4,5,0]
np_typ=np.array(l1,dtype=bool,)
print(np_typ)

[ True  True  True  True False]


In [66]:
#arrange the no
import numpy as np
arr=np.arange(2,12)
print(arr)


[ 2  3  4  5  6  7  8  9 10 11]
